#!/usr/bin/env bash
#
# Loop each episode and generate a tab-separated list of all episodes seen to
# stdout
#
# Author: Dave Eddy <dave@daveeddy.com>
# Date: April 05, 2025
# License: MIT

dir=${1:-../blogs}

for pt in "$dir"/blog-*/meta.txt; do
	mapfile -t lines < "$pt"

	# read the meta at the top
	title=${lines[0]}
	num=${title%%.*}
	title=${title#*. }
	desc=${lines[1]}
        
	# read the key values pairs at the bottom
	lines=("${lines[@]:2}")
	declare -A links=()
	for line in "${lines[@]}"; do
		read -r key value <<< "$line"
		[[ -n $key && -n $value ]] || continue
		links[$key]=$value
	done

	link=${links[medium]}
	[[ -n $link  ]] || continue

	printf '%s\t' "$num" "$title" "$desc" "$link"
	echo
done
