#!/usr/bin/env bash
#
# Print the socials - indended to be passed to `tools/box`
#
# Author: Dave Eddy <dave@daveeddy.com>
# Date: April 05, 2025
# License: MIT

. ./theme || exit

readarray -t SOCIALS << "EOF"
Linkedin|https://www.linkedin.com/in/zishan-ansari-307a58189/
Github|https://github.com/0xZ15H4N
Ctftime.org|https://ctftime.org/team/364395
EOF

UNDERLINE=$'\x1b[3m'

for line in "${SOCIALS[@]}"; do
	IFS='|' read -r name url <<< "$line"

	echo -n "$COLOR2$name$RST"
	echo -n '|'
	echo -n "$UNDERLINE$COLOR2$url$RST"
	echo
done
